version: '3'

services:
  frontend:
    build: frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 8000:8000
    # Frontend starts after backend
    depends_on:
      - backend
    environment:
      - BACKEND_PORT=${BACKEND_PORT}

  backend:
    build: backend
    command: npm run dev
    # Mount these folders to the container to update them
    # without restarting docker-compose
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/db:/usr/src/app/db
    ports:
      - ${BACKEND_PORT}:9000
